"""
FEMMT Bridge - Export PyOpenMagnetics designs to FEMMT.

FEMMT (FEM Magnetics Toolbox) is an open-source Python tool for
electromagnetic FEM simulation of inductors and transformers.

This bridge converts PyOpenMagnetics DesignResult objects into
executable FEMMT Python scripts for detailed FEM analysis.

GitHub: https://github.com/upb-lea/FEM_Magnetics_Toolbox
"""

from dataclasses import dataclass
from typing import Optional
import textwrap

from ..results import DesignResult


@dataclass
class FEMMTConfig:
    """Configuration for FEMMT export."""
    working_directory: str = "./femmt_simulation"
    mesh_accuracy: float = 0.5
    simulation_name: str = "pyom_design"
    include_air_gaps: bool = True
    include_insulation: bool = True


class FEMMTExporter:
    """Export PyOpenMagnetics designs to FEMMT format."""

    # Core family to FEMMT core type mapping
    CORE_TYPE_MAP = {
        "E": "E",
        "EE": "E",
        "ETD": "E",
        "EFD": "E",
        "ER": "E",
        "EQ": "E",
        "PQ": "PQ",
        "PM": "PM",
        "RM": "RM",
        "P": "P",
        "POT": "POT",
        "EP": "EP",
        "ELP": "ELP",
        "U": "U",
        "UI": "U",
        "UU": "U",
    }

    # Material to FEMMT material mapping
    MATERIAL_MAP = {
        "3C90": "N87",     # Similar characteristics
        "3C92": "N87",
        "3C94": "N87",
        "3C95": "N95",
        "3C96": "N97",
        "3C97": "N97",
        "3F3": "N87",
        "3F4": "N49",
        "N27": "N27",
        "N30": "N30",
        "N49": "N49",
        "N87": "N87",
        "N95": "N95",
        "N97": "N97",
    }

    def __init__(self, config: Optional[FEMMTConfig] = None):
        self.config = config or FEMMTConfig()

    def export(self, design: DesignResult) -> str:
        """
        Export a DesignResult to FEMMT Python script.

        Args:
            design: A DesignResult from PyOpenMagnetics design process

        Returns:
            str: Executable Python script for FEMMT simulation
        """
        script = self._generate_header()
        script += self._generate_imports()
        script += self._generate_core_setup(design)
        script += self._generate_winding_setup(design)
        script += self._generate_simulation(design)
        script += self._generate_footer()

        return script

    def _generate_header(self) -> str:
        return textwrap.dedent(f'''
            """
            FEMMT Simulation Script
            Generated by PyOpenMagnetics FEMMT Bridge

            Simulation: {self.config.simulation_name}
            """

        ''')

    def _generate_imports(self) -> str:
        return textwrap.dedent('''
            import femmt as fmt
            import os

        ''')

    def _generate_core_setup(self, design: DesignResult) -> str:
        # Determine core type from shape name
        core_type = "E"  # Default
        for prefix, femmt_type in self.CORE_TYPE_MAP.items():
            if design.core.upper().startswith(prefix):
                core_type = femmt_type
                break

        # Map material
        femmt_material = self.MATERIAL_MAP.get(design.material, "N87")

        return textwrap.dedent(f'''
            # Core Configuration
            working_directory = "{self.config.working_directory}"
            os.makedirs(working_directory, exist_ok=True)

            # Create geometry object
            geo = fmt.MagneticComponent(
                component_type=fmt.ComponentType.Inductor,
                working_directory=working_directory,
                verbosity=fmt.Verbosity.Silent
            )

            # Core dimensions from PyOpenMagnetics: {design.core}
            # Note: Adjust dimensions based on actual core datasheet
            core = fmt.Core(
                core_type=fmt.CoreType.Single,
                core_inner_diameter=0.015,    # Adjust based on {design.core}
                window_w=0.012,               # Adjust based on {design.core}
                window_h=0.020,               # Adjust based on {design.core}
                material=fmt.Material.{femmt_material}
            )
            geo.set_core(core)

        ''')

    def _generate_winding_setup(self, design: DesignResult) -> str:
        # Parse wire diameter from wire string
        wire_diameter = 0.0005  # Default 0.5mm
        if design.primary_wire:
            # Try to extract diameter from wire string like "AWG 24" or "0.51mm"
            if "mm" in design.primary_wire.lower():
                try:
                    import re
                    match = re.search(r'(\d+\.?\d*)\s*mm', design.primary_wire.lower())
                    if match:
                        wire_diameter = float(match.group(1)) / 1000
                except Exception:
                    pass

        air_gap_code = ""
        if design.air_gap_mm > 0:
            air_gap_code = textwrap.dedent(f'''
            # Air gap: {design.air_gap_mm:.3f} mm
            geo.set_air_gaps(fmt.AirGaps(fmt.AirGapMethod.Center, geo.core))
            geo.air_gaps.add_air_gap(
                fmt.AirGapLegPosition.CenterLeg,
                {design.air_gap_mm / 1000:.6f}
            )
            ''')

        return textwrap.dedent(f'''
            # Winding Configuration
            # Primary: {design.primary_turns} turns, {design.primary_wire}
            winding = fmt.Conductor(
                conductor_type=fmt.ConductorType.RoundLitz,
                conductor_diameter={wire_diameter:.6f},
                number_strands=50,              # Adjust for litz wire
                strand_diameter=0.00005         # Adjust for litz wire
            )

            geo.set_winding_windows([fmt.WindingWindow(core.window_w, core.window_h)])

            vww = geo.split_window(fmt.WindingWindowSplit.NoSplit)

            winding_scheme = fmt.WindingScheme.FoilVertical if {design.primary_turns} > 50 else fmt.WindingScheme.Full

            geo.set_winding(
                winding_scheme=winding_scheme,
                winding_windows=vww,
                conductor_arrangement=fmt.ConductorArrangement.Square,
                conductor=winding,
                turns={design.primary_turns}
            )
            {air_gap_code}
        ''')

    def _generate_simulation(self, design: DesignResult) -> str:
        return textwrap.dedent(f'''
            # Simulation Setup
            # Create mesh
            geo.create_model(freq=100000, pre_visualize_geometry=False)

            # Run simulation
            geo.single_simulation(
                freq=100000,
                current=[1.0],          # Adjust excitation current
                phi_deg=[0],
                show_fem_simulation_results=True
            )

            # Results
            print("\\n=== FEMMT Simulation Results ===")
            print(f"PyOpenMagnetics predicted losses: {design.total_loss_w:.3f} W")
            print("FEMMT calculated losses: see visualization")

        ''')

    def _generate_footer(self) -> str:
        return textwrap.dedent('''
            if __name__ == "__main__":
                print("FEMMT simulation complete!")
        ''')


def export_to_femmt(design: DesignResult, config: Optional[FEMMTConfig] = None) -> str:
    """
    Export a PyOpenMagnetics design to FEMMT Python script.

    Args:
        design: DesignResult from PyOpenMagnetics
        config: Optional FEMMTConfig for customization

    Returns:
        str: Executable FEMMT Python script

    Example:
        >>> from api.design import Design
        >>> results = Design.buck().vin(12,24).vout(5).iout(3).fsw(500e3).solve()
        >>> if results:
        ...     script = export_to_femmt(results[0])
        ...     with open("femmt_sim.py", "w") as f:
        ...         f.write(script)
    """
    exporter = FEMMTExporter(config)
    return exporter.export(design)
